//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Tom.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraNode) DeepCopyInto(out *TerraNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraNode.
func (in *TerraNode) DeepCopy() *TerraNode {
	if in == nil {
		return nil
	}
	out := new(TerraNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TerraNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraNodeList) DeepCopyInto(out *TerraNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TerraNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraNodeList.
func (in *TerraNodeList) DeepCopy() *TerraNodeList {
	if in == nil {
		return nil
	}
	out := new(TerraNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TerraNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraNodeSpec) DeepCopyInto(out *TerraNodeSpec) {
	*out = *in
	out.Unit = in.Unit
	out.Service = in.Service
	out.Install = in.Install
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraNodeSpec.
func (in *TerraNodeSpec) DeepCopy() *TerraNodeSpec {
	if in == nil {
		return nil
	}
	out := new(TerraNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraNodeStatus) DeepCopyInto(out *TerraNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraNodeStatus.
func (in *TerraNodeStatus) DeepCopy() *TerraNodeStatus {
	if in == nil {
		return nil
	}
	out := new(TerraNodeStatus)
	in.DeepCopyInto(out)
	return out
}
